package javasnes.util.operators.assign;

import javasnes.util.operators.SnesOperator;
import javasnes.util.types.vars.abstracts.array.SnesTypeArray;

/**
 * The OperatorArrayIndex class represents the assignment of a value to an index of an 
 * array in the SNES development. It is used to assign a value to a specific location in
 * an array.
 */
public class OperatorArrayIndex extends SnesOperator {

    /**
     * The array to be indexed.
     */
    public SnesTypeArray array;

    /**
     * The index(es) of the array.
     */
    public short[] index;

    /**
     * The number of dimensions of the array.
     */
    public short dimensions;

    /**
     * The value to be assigned in the array's index.
     */
    public String value;

    /**
     * Constructor for the OperatorArrayIndex class.
     * For one-dimensional arrays.
     * @param array the array to be indexed
     * @param index the index
     * @param value the value to be assigned in the array's index
     */
    public OperatorArrayIndex(
        SnesTypeArray array, short index, String value
    ) {
        this.array = array;
        this.index = new short[1]; this.index[0] = index;
        this.dimensions = 1;
        this.value = value;

        this.generateSourceCode();
    }

    /**
     * Constructor for the OperatorArrayIndex class.
     * For multi-dimensional arrays.
     * @param array the array to be indexed
     * @param index the indexes
     * @param dimensions the number of dimensions
     * @param value the value to be assigned in the array's index
     */
    public OperatorArrayIndex(
        SnesTypeArray array, short[] index, short dimensions, String value
    ) {
        this.array = array;
        this.index = index;
        this.dimensions = dimensions;
        this.value = value;

        this.generateSourceCode();
    }

    /**
     * Generates the source code for the array index operator.
     * 
     * This method sets the sourceCode field to the source code generated by the getSourceCode method.
     */
    public final void generateSourceCode() {

        this.sourceCode = this.getSourceCode();

    }

    /**
     * Generates the source code for the array index operator.
     * 
     * If the number of dimensions is 1, the source code will be in the format of "array[index] = value;".
     * If the number of dimensions is greater than 1, the source code will be in the format of "array[index1][index2]...[indexN] = value;".
     * 
     * For example:
     * <pre>
     * arrayName[index] = value;
     * arrayName[index1][index2]...[indexN] = value;
     * </pre>
     * 
     * @return the source code for the array index operator
     */
    @Override
    public String getSourceCode() {

        if (dimensions == 1) {

            return this.array.name + "[" + this.index[0] + "] = " + this.value + ";";

        } else {

            StringBuilder sb = new StringBuilder();
            sb.append(this.array.name).append("[").append(this.index[0]).append("]");

            for (int i = 1; i < dimensions; i++) {
                sb.append("[").append(index[i]).append("]");
            }

            sb.append(" = ").append(value).append(";");

            return sb.toString();

        }

    }
    
}
