package javasnes.util.operators.assign;

import javasnes.util.operators.SnesOperator;

/**
 * The OperatorAssign class represents the assignment of a value to a variable in the
 * SNES development context. It is used to assign a value to a variable.
 */
public class OperatorAssign extends SnesOperator {

    /**
     * The incrementSignal field represents the signal used to increment the value of 
     * a variable. Can be null if the variable is not incremented.
     * 
     * For example:
     *   
     * <pre>
     *   List<SnesInstruction> instructions = new ArrayList<>();
     *   SnesU8 myVar = new SnesU8("myVar", "8");
     *   Operator op = new OperatorAssign(myVar, '+', "1");
     *   instructions.add(myVar);
     *   instructions.add(op);
     *   SnesProcess process = new SnesProcess(
     *      "example", 0, null, null, instructions, null
     *   );
     *   process.generateSourceCode();
     *   System.out.println(process.getSourceCode());
     *      
     *   // Expected output:
     *   void example(void) {
     *      u8 myVar = 8;
     *      myVar += 1;
     *      return;
     *   }
     * </pre>
     * 
     * Some examples of incrementSignals:
     * 
     *   '+': myVar += 1
     *   '-'': myVar -= 1
     *   '*': myVar *= 2
     *   '/': myVar /= 2
     *   '%': myVar %= 2
     * 
     */
    public Character incrementSignal = null;

    /**
     * The value field represents the value to be assigned to the variable.
     */
    public String value;

    /**
     * The variableName field represents the name of the variable to be assigned.
     */
    public String variableName;

    /**
     * Constructor for OperatorAssign.
     * This constructor sets the variableName and value fields.
     * If you want to define the incrementSignal field, use the other constructor.
     * @param variableName
     * @param value
     */
    public OperatorAssign(String variableName, String value) {

        this.variableName = variableName;
        this.value = value;

        this.generateSourceCode();

    }

    /**
     * Constructor for OperatorAssign.
     * This constructor sets the variableName, value, and incrementSignal fields.
     * @param variableName
     * @param value
     * @param incrementSignal
     */
    public OperatorAssign(String variableName, String value, char incrementSignal) {

        this.variableName = variableName;
        this.value = value;
        this.incrementSignal = incrementSignal;

        this.generateSourceCode();

    }

    /**
     * Generates the source code for the assign operator.
     * This method sets the sourceCode field to the source code generated by the getSourceCode method.
     */
    public final void generateSourceCode() {

        this.sourceCode = this.getSourceCode();
        
    }

    /**
     * Generates the source code representation of the assign operator.
     * 
     * If the incrementSignal field is not null, the source code will be in the format of "variableName incrementSignal = value;".
     * Otherwise, the source code will be in the format of "variableName = value;".
     * 
     * @return the source code for the assign operator
     */
    @Override
    public final String getSourceCode() {

        if (this.incrementSignal != null) {

            return this.variableName + " " + this.incrementSignal + "= " + this.value + ";";
        
        } else {

            return this.variableName + " = " + this.value + ";";

        }
        
    }
    
}
