package javasnes.util.types;

import java.util.Deque;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.LinkedList;
import java.util.Map;
import java.util.Set;

public class Processor {

    /**
     * A map of processes to their arguments.
     * 
     * The map contains all the processes that have been added to the processor,
     * along with their arguments. The processes are identified by their names,
     * and the arguments are the ones that were provided when the process was added.
     */
    private Map<SnesProcess, String[]> processes = new LinkedHashMap<>();

    private Deque<SnesProcess> processesOrder = new LinkedList<>();

    /**
     * Returns a map of processes to their arguments.
     * 
     * The map contains all the processes that have been added to the processor,
     * along with their arguments. The processes are identified by their names,
     * and the arguments are the ones that were provided when the process was added.
     * 
     * @return a map of processes to their arguments
     */
    public Map<SnesProcess, String[]> getProcesses() { 

        return this.processes;

    }

    /**
     * A getter for the processesOrder field.
     * 
     * This method returns the Deque of SNES processes in the order they were added to the processor.
     * 
     * @return the Deque of SNES processes in the order they were added to the processor
     */
    public Deque<SnesProcess> getProcessesOrder() {

        return processesOrder;

    }

    /**
     * Sets the order of SNES processes in the processor.
     * 
     * This method sets the order of SNES processes in the processor to the given Deque.
     * The order of the processes is important because it determines the order of
     * the generated source code.
     * 
     * @param processesOrder the Deque of SNES processes to set as the order of the processor
     */
    public void setProcessesOrder(Deque<SnesProcess> processesOrder) {

        this.processesOrder = processesOrder;
        
    }

    /**
     * Default constructor for the Processor class.
     * 
     * Do nothing :P
     */
    public Processor() {  }

    /**
     * Constructor for the Processor class.
     * 
     * It overrides this.processes with the given map of processes to their arguments.
     * 
     * @param processes a map of processes to their arguments
     */
    public Processor(Map<SnesProcess, String[]> processes) {

        this.processes = processes;

        for (SnesProcess process : this.processes.keySet()) {

            this.processesOrder.addLast(process);

        }

    }

    /**
     * Adds a process to the processor.
     * 
     * The process is identified by its name and the arguments it takes.
     * If a process with the same name already exists, its arguments will be overwritten.
     * 
     * @param process the process to be added
     * @param args the arguments of the process
     */
    public void addProcess(SnesProcess process, String[] args) {

        this.processes.put(process, args);

        this.processesOrder.addLast(process);

    }

    /**
     * Removes a process from the processor.
     * 
     * The process is identified by its name. If no process with the given name is found, the method does nothing.
     * 
     * @param processName the name of the process to be removed
     */
    public void removeProcess(String processName) {

        for (SnesProcess process : this.processesOrder) {

            if (process.name.equals(processName)) {

                this.processes.remove(process);
                this.processesOrder.remove(process);

            }

        }

    }

    /**
     * Gets the arguments of the given process.
     * 
     * @param processName the name of the process
     * @return the arguments of the process if found, otherwise null
     */
    public String[] getProcessArgs(String processName) {

        for (SnesProcess process : this.processesOrder) {

            if (process.name.equals(processName)) {

                return this.processes.get(process);

            }

        }

        return null;

    }

    /**
     * Returns the C source code of the given process.
     * 
     * The source code is the C code that is generated by the process when calling
     * {@link SnesProcess#getSourceCode()}.
     * 
     * If the process is not found in the map, null is returned.
     * 
     * @param processName the name of the process
     * @return the source code of the process if found, otherwise null
     */
    public String getProcessSourceCode(String processName) {

        for (SnesProcess process : this.processesOrder) {

            if (process.name.equals(processName)) {

                return process.getSourceCode();

            }

        }

        return null;

    }

    /**
     * Generates the C source code for the processor function.
     * 
     * This method constructs the C source code for the processor function,
     * which calls all the processes provided in the constructor.
     * 
     * If a process has not been given any arguments, it will be called
     * without any arguments. If a process has been given arguments, it
     * will be called with those arguments.
     * 
     * The generated source code is returned as a string.
     */
    @SuppressWarnings("StringConcatenationInsideStringBufferAppend")
    public String generateSourceCode() {

        StringBuilder sb = new StringBuilder();

        sb.append("void processor(void) {\n");

        for (SnesProcess process : this.processesOrder) {

            if (process.sourceCode == null) {

                process.getSourceCode();

            }

            if (this.processes.get(process) == null) {

                sb.append("\t" + process.name + "();\n");

                continue;

            }

            sb.append("\t" + process.name + "(" + String.join(", ", this.processes.get(process)) + ");\n");

        }

        sb.append("\treturn;\n");
        sb.append("}\n");

        return sb.toString();

    }


    /**
     * Validates that all process names are unique.
     * 
     * This method will throw an IllegalArgumentException if it finds any duplicate process names.
     * 
     * @throws IllegalArgumentException if a duplicate process name is found.
     */
    public void validateNotDuplicateProcessNames() throws IllegalArgumentException {

        Set<String> processNames = new HashSet<>();

        for (SnesProcess process : this.processes.keySet()) {

            if (processNames.contains(process.name)) {

                throw new IllegalArgumentException("Duplicate process name: " + process.name);

            }

            processNames.add(process.name);

        }

    }
    
}
